table PagesForUsers
	lineageTag: 418228c4-c3bf-4ea3-bf86-433ea46cd7da

	measure 'User Logged In' = USERPRINCIPALNAME()
		lineageTag: 99df4088-309a-4a4f-b757-7eac07a46cde

	column User
		lineageTag: 37a82d8d-3a4d-45d2-a834-63e86efc7cfc
		summarizeBy: none
		isNameInferred
		sourceColumn: [User]

		annotation SummarizationSetBy = Automatic

	column Page
		lineageTag: a303abcd-54cb-4e1c-8af4-9a22b66d9f16
		summarizeBy: none
		isNameInferred
		sourceColumn: [Page]

		annotation SummarizationSetBy = Automatic

	partition PagesForUsers = calculated
		mode: import
		source = ```
				
				DATATABLE(
				    "User", STRING,
				    "Page", STRING,
				    {
				        {"Malek.chkoundali@esprit.tn", "Supplier Manager 1"},
				        {"Malek.chkoundali@esprit.tn", "Supplier Manager2"},
				         {"Malek.chkoundali@esprit.tn", "Supplier Manager2"},
				
				        {"Aya.Arfaoui@esprit.tn", "Risk Manager 1"},
				        {"Aya.Arfaoui@esprit.tn", "Risk Manager2"},
				
				        {"SeifEddine.Kallela@esprit.tn", "DAF 1"},
				        {"SeifEddine.Kallela@esprit.tn", "DAF2"},
				
				        {"Aya.Arfaoui@esprit.tn", "Home"},
				        {"Malek.Chkoundali@esprit.tn", "Home"},
				        {"SeifEddine.Kallela@esprit.tn", "Home"},
				
				        {"Aya.Arfaoui@esprit.tn", "OVERVIEW"},
				        {"Malek.chkoundali@esprit.tn", "OVERVIEW"},
				        {"SeifEddine.Kallela@esprit.tn", "OVERVIEW"}
				    }
				)
				
				```

	annotation PBI_Id = d00f52bc2cee42b5a142183d28e35f49

