table supplier_risk_management
	lineageTag: 7e6abe70-21f1-4773-9906-15a340e82d0f

	column Fk_Supplier
		dataType: string
		lineageTag: ea5bae85-c937-4e68-81e6-9e1d7b611e0e
		summarizeBy: none
		sourceColumn: Fk_Supplier

		annotation SummarizationSetBy = Automatic

	column Total_Invoices
		dataType: int64
		formatString: 0
		lineageTag: 42ba2caf-af38-4af5-a6d3-11ed0736467e
		summarizeBy: sum
		sourceColumn: Total_Invoices

		annotation SummarizationSetBy = Automatic

	column Mean_Payment_Delay
		dataType: double
		lineageTag: 7ab1e0a1-9249-43d8-9917-cd001c042e59
		summarizeBy: sum
		sourceColumn: Mean_Payment_Delay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Std_Payment_Delay
		dataType: double
		lineageTag: 884d3347-5846-4bed-89e7-3220c087e2cc
		summarizeBy: sum
		sourceColumn: Std_Payment_Delay

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Late_Payment_Ratio
		dataType: double
		lineageTag: 2a5d532d-4ede-47da-ba10-e81e644ea4fc
		summarizeBy: sum
		sourceColumn: Late_Payment_Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Paid_Ratio
		dataType: double
		lineageTag: 1f0c71e3-e670-41d2-a0ef-0ed21159a925
		summarizeBy: sum
		sourceColumn: Paid_Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Partial_Payment_Ratio
		dataType: int64
		formatString: 0
		lineageTag: b2b5fc6b-2497-4b7a-91ed-f12f6b890aab
		summarizeBy: sum
		sourceColumn: Partial_Payment_Ratio

		annotation SummarizationSetBy = Automatic

	column Unpaid_Ratio
		dataType: double
		lineageTag: 13361742-dd6d-4e37-85d4-4da6310b98da
		summarizeBy: sum
		sourceColumn: Unpaid_Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Approval_Rate
		dataType: double
		lineageTag: 733c9279-f793-483f-9569-a6cbb266b71f
		summarizeBy: sum
		sourceColumn: Approval_Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Problem_Payment_Ratio
		dataType: double
		lineageTag: daa9c07a-4adb-4b3b-985a-96d369d350fc
		summarizeBy: sum
		sourceColumn: Problem_Payment_Ratio

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Total_Disputes
		dataType: int64
		formatString: 0
		lineageTag: 8a1c4ef6-ce2d-4696-afb6-02aa520c4be3
		summarizeBy: sum
		sourceColumn: Total_Disputes

		annotation SummarizationSetBy = Automatic

	column Avg_Dispute_Duration
		dataType: int64
		formatString: 0
		lineageTag: 8fbb126d-d8dd-4fa7-981e-7249a40404c5
		summarizeBy: sum
		sourceColumn: Avg_Dispute_Duration

		annotation SummarizationSetBy = Automatic

	column Dispute_Resolution_Rate
		dataType: double
		lineageTag: e94d80c1-e118-42bd-878e-778026d233c5
		summarizeBy: sum
		sourceColumn: Dispute_Resolution_Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Payment_Consistency
		dataType: double
		lineageTag: c629ce6a-d56c-428c-96d6-90c5decb87ad
		summarizeBy: sum
		sourceColumn: Payment_Consistency

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Dispute_Intensity
		dataType: int64
		formatString: 0
		lineageTag: e1956fbd-dcee-435c-8125-818f451f74ef
		summarizeBy: sum
		sourceColumn: Dispute_Intensity

		annotation SummarizationSetBy = Automatic

	column Financial_Risk_Score
		dataType: double
		lineageTag: 4c023400-a38d-44bd-a37c-aa2b0eeb4dcd
		summarizeBy: sum
		sourceColumn: Financial_Risk_Score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PCA_X
		dataType: double
		lineageTag: 3ace0838-0040-435b-a1a9-07da5cf24f5d
		summarizeBy: sum
		sourceColumn: PCA_X

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PCA_Y
		dataType: double
		lineageTag: 1b819627-ac79-4098-bcf6-9bd153314dae
		summarizeBy: sum
		sourceColumn: PCA_Y

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Cluster
		dataType: int64
		formatString: 0
		lineageTag: bb029a13-1af0-497f-9ebb-e1144c70c17d
		summarizeBy: sum
		sourceColumn: Cluster

		annotation SummarizationSetBy = Automatic

	column Cluster_Name
		dataType: string
		lineageTag: f3a32649-a3e2-4236-95eb-065df99ac11f
		summarizeBy: none
		sourceColumn: Cluster_Name

		annotation SummarizationSetBy = Automatic

	partition supplier_risk_management = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Temp\supplier_risk_management.csv"),[Delimiter=";", Columns=20, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"Fk_Supplier", type text}, {"Total_Invoices", Int64.Type}, {"Mean_Payment_Delay", type number}, {"Std_Payment_Delay", type number}, {"Late_Payment_Ratio", type number}, {"Paid_Ratio", type number}, {"Partial_Payment_Ratio", Int64.Type}, {"Unpaid_Ratio", type number}, {"Approval_Rate", type number}, {"Problem_Payment_Ratio", type number}, {"Total_Disputes", Int64.Type}, {"Avg_Dispute_Duration", Int64.Type}, {"Dispute_Resolution_Rate", type number}, {"Payment_Consistency", type number}, {"Dispute_Intensity", Int64.Type}, {"Financial_Risk_Score", type number}, {"PCA_X", type number}, {"PCA_Y", type number}, {"Cluster", Int64.Type}, {"Cluster_Name", type text}})
				in
				    #"Type modifié"

	annotation PBI_ResultType = Table

